WebProgrammingTerm.MVC/Controllers/AboutUsController.cs
using System.Web.Mvc;

namespace WebProgrammingTerm.MVC.Controllers;

public class AboutUsController : Controller
{
    public ActionResult AboutUsIndex()
    {
        return View();
    }
}

WebProgrammingTerm.MVC/Controllers/ContactController.cs
using System.Web.Mvc;

namespace WebProgrammingTerm.MVC.Controllers;

public class ContactController : Controller
{
    // GET
    public ActionResult ContactIndex()
    {
        return View();
    }
}

WebProgrammingTerm.MVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using SharedLibrary.DTO;
using WebProgrammingTerm.MVC.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class ProductController : Controller
{
    public async Task<ActionResult> Index(string id)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        var productJsonObject = await ProductServices.GetProduct(id);

        if (!productJsonObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (productJsonObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");


        if (accessToken is not null)
        {
            var userJsonObject = await FavoritesService.GetFavorites(accessToken);
        
            if (!userJsonObject.HasValues)
                return RedirectToAction("Index", "ErrorPage");

            if (userJsonObject["errors"].HasValues)
                return RedirectToAction("Index", "ErrorPage");
            var model = new ProductModel()
            {
                ProductWGetDto = productJsonObject["data"].ToObject<ProductWCommentDto>(),
                UserFavoritesDto = userJsonObject["data"].ToObject<UserFavoritesListDto>()
            };
            model.ProductWGetDto.Size = productJsonObject["data"]["productDetail"]["size"].ToString();

            return View(model);

        }
        else
        {
            var model = new ProductModel()
            {
                ProductWGetDto = productJsonObject["data"].ToObject<ProductWCommentDto>(),
                UserFavoritesDto = new UserFavoritesListDto()
            };
            return View(model);
        }
        
    }
    public async Task<ActionResult> Search(string searchTerm = "",int page = 1)
    {

        if (page < 1)
        {
            page = 1;
        }
        var productObject = await ProductServices.GetProductFromName(searchTerm, page);

        if (!productObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (productObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");


        ViewData["searchterm"] = searchTerm;
        ViewData["page"] = page;
        var products = productObject["data"].ToObject<List<ProductGetDto>>() ?? new List<ProductGetDto>();



        return View(products);
    }

    public async Task<ActionResult> SearchByCategory(string searchTerm = "",int page = 1)
    {

        if (page < 1)
        {
            page = 1;
        }
        var productObject = await ProductServices.GetProductFromCategory(searchTerm, page);

        if (!productObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (productObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");


        ViewData["searchterm"] = searchTerm;
        ViewData["page"] = page;

        var products = productObject["data"].ToObject<List<ProductGetDto>>();

        if (products is null)
        {
            products = new List<ProductGetDto>();
        }
        
        if (products.Count ==0 && page >2)
        {
            ViewData["NXT"] = false;

            return RedirectToAction("SearchByCategory", new { searchTerm = searchTerm, page = page-1 });
            
        }
        ViewData["NXT"] = true;

        return View("Search",products);
    }

 
}

WebProgrammingTerm.MVC/Controllers/ProfileController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using SharedLibrary.DTO;
using SharedLibrary.Models;
using WebProgrammingTerm.MVC.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class ProfileController : Controller
{
    [HttpGet]
    public async Task<ActionResult> ProfileIndex()
    {
        if (TempData["ModelState"] is ModelStateDictionary modelState)
            ModelState.Merge(modelState);

        if (TempData.ContainsKey("PasswordChanged"))
        
            ViewData["PasswordChanged"] = true;

        var token = Request.Cookies["accessToken"]?.Value;
        
        if (token is null) 
            return RedirectToAction("SignIn", "Account");
        
        var userJson = await UserServices.GetUserProfileInfo(token);
        
        if (!userJson.HasValues)
        {
            Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1);

            return RedirectToAction("Index", "ErrorPage");
        }
        
        var userData = userJson["data"];
        var user = userData.ToObject<User>();
        
        
        return View(new UserModels()
        {
            User = user
        });
    }
    
    
    [HttpPost]
    public async Task<ActionResult> SaveProfile(AppUserUpdateDto appUserUpdateDto,string birthdate)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        var refreshToken = Request.Cookies["refreshToken"]?.Value;
        
        if (string.IsNullOrEmpty(accessToken) || string.IsNullOrEmpty(refreshToken))
            return RedirectToAction("SignIn", "Account");

        
        var userJson = await UserServices.UpdateUserProfile(appUserUpdateDto,accessToken);

        if (!userJson.HasValues)
            return RedirectToAction("Index", "ErrorPage");
        
        var userRefreshTokenJson =await UserServices.CreateTokenByRefreshToken(refreshToken);
        
        Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
        Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1);
        
        if (!userRefreshTokenJson.HasValues)
            return RedirectToAction("Index", "ErrorPage");
        

        var cookies = UserServices.AddCookies(userRefreshTokenJson);
        foreach (var cookie in cookies)
        {
            Response.Cookies.Add(cookie);
        }
        appUserUpdateDto.BirthDate = birthdate;
        
        return RedirectToAction("ProfileIndex");

    }

    [HttpPost]
    public async Task<ActionResult> UpdatePassword(UserUpdatePasswordDto userUpdatePasswordDto)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        var refreshToken = Request.Cookies["refreshToken"]?.Value;
        TempData["PasswordChanged"] = false;

        if (string.IsNullOrEmpty(accessToken) || string.IsNullOrEmpty(refreshToken))
            return RedirectToAction("SignIn", "Account");

        if (string.CompareOrdinal(userUpdatePasswordDto.NewPassword, userUpdatePasswordDto.NewPasswordConfirm) != 0)
        {
            ModelState.AddModelError("Password","Password and Confirm password does not match");
            return RedirectToAction("ProfileIndex");
        }

        var jsonObject = await UserServices.UpdateUserPassword(userUpdatePasswordDto, accessToken);
        if (!jsonObject.HasValues)
        {
            Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1);
            RedirectToAction("Index", "ErrorPage");
        }
        if (!jsonObject["errors"]!.HasValues)
        {
            Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1); 
            
            var cookies =UserServices.AddCookies(jsonObject);
            
            foreach (var cookie in cookies)
            {
                Response.Cookies.Add(cookie);
            }
            TempData["PasswordChanged"] = true;

        }
        else
        {
            foreach (var error in jsonObject["errors"])
            {
                if (error.ToString().Contains("ssword")  )
                    ModelState.AddModelError("Password",$"{error}");
            }
            TempData["ModelState"] = ModelState;

        }
        return RedirectToAction("ProfileIndex");
    }
    

}

WebProgrammingTerm.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="icon" href="~/favicon.ico" type="image/x-icon" />

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/Content/BookerrCSS/Header.css?v2">
    <link rel="stylesheet" type="text/css" href="/Content/BookerrCSS/Footer.css?v1">
    <script src="~/Scripts/BookerrScripts/CartScript.js?v18"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header>
        <div id="topLayer">
            <div id="layout">
                <img src="~/Content/WebAssets/LineforTop@2x.png" style="opacity: 0.6;">
                <h1 align="center">
                    <font face="Montserrat" size="5" style="color:rgb(19, 19, 19);">Up to 50% discounts for World Book
                        Day!
                        CODE: WBD50IKU </font>
                </h1>
            </div>
            <div id="about-contact">
                <div>
                    <font color="#828285">

                        <body vlink="#828285"><a href="@Url.Action("AboutUsIndex", "AboutUs")">About</a>&nbsp;&nbsp;&nbsp;
                        <a href="@Url.Action("ContactIndex", "Contact")">Contact</a>
                        </body>
                    </font>

                </div>
            </div>

            <hr class="myhr">

            <div class="bookerr-image">
                <a href="@Url.Action("Home", "Home")">
                    <img src="~/Content/WebAssets/BOOKERRLogo_Pink.svg">
                </a>
            </div>
            
                @using (Html.BeginForm("Search", "Product", FormMethod.Post))
                {
                    <div class="search-bar">
                        <input type="text" name="searchTerm" placeholder="Search">
                    </div>
                }

            <div class="profile-image">
                <a href=@Url.Action("ProfileIndex", "Profile")>
                    <img src="~/Content/WebAssets/ProfileIcon.svg">
                </a>
            </div>

            <div class="sepet-image">
                @{
                    var token = "";
                    if (Request.Cookies["accessToken"]?.Value !=null)
                    {
                        token = Request.Cookies["accessToken"].Value;
                    }
                }
                <a href="#" onclick="SenRequestForAddToCart('@token')">
                    <img src="~/Content/WebAssets/CartIcon.svg">
                </a>
            </div>
        </div>
        <div class="vertical-stripe">
            <a href="@Url.Action("SearchByCategory","Product",new{searchTerm = "Roman",page=1})" class="stripe-item">Novel</a>
            <a href="@Url.Action("SearchByCategory","Product",new{searchTerm = "Kişisel Gelişim",page=1})" class="stripe-item">Self Improvement</a>
            <a href="@Url.Action("SearchByCategory","Product",new{searchTerm = "Çocuk",page=1})" class="stripe-item">Kids</a>
            <a href="@Url.Action("SearchByCategory","Product",new{searchTerm = "E-kitap",page=1})" class="stripe-item">E Book</a>
            <a href="@Url.Action("SearchByCategory","Product",new{searchTerm = "Egitim",page=1})" class="stripe-item">Education</a>
            <a href="@Url.Action("SearchByCategory","Product",new{searchTerm = "Edebiyat",page=1})" class="stripe-item">Literature</a>
        </div>
    </header>

        @RenderBody()
        <hr/>
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col">
                    <h4>

                        <body vlink="#808285 "> </body><a href="#" style="color:#808285">Main Category 1</a>
                    </h4>
                    <ul>
                        <li><a href="#">Sub Category 1</a></li>
                        <li><a href="#">Sub Category 2</a></li>
                        <li><a href="#">Sub Category 3</a></li>
                        <li><a href="#">Sub Category 4</a></li>
                        <li><a href="#">Sub Category 5</a></li>
                        <li><a href="#">Sub Category 6</a></li>
                        <li><a href="#">Sub Category 7</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>

                        <body vlink="#808285 "> </body><a href="#" style="color:#808285">Main Category 2</a>
                    </h4>
                    <ul>
                        <li><a href="#">Sub Category 1</a></li>
                        <li><a href="#">Sub Category 2</a></li>
                        <li><a href="#">Sub Category 3</a></li>
                        <li><a href="#">Sub Category 4</a></li>
                        <li><a href="#">Sub Category 5</a></li>
                        <li><a href="#">Sub Category 6</a></li>
                        <li><a href="#">Sub Category 7</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>

                        <body vlink="#808285 "> </body><a href="#" style="color:#808285">Main Category 3</a>
                    </h4>
                    <ul>
                        <li><a href="#">Sub Category 1</a></li>
                        <li><a href="#">Sub Category 2</a></li>
                        <li><a href="#">Sub Category 3</a></li>
                        <li><a href="#">Sub Category 4</a></li>
                        <li><a href="#">Sub Category 5</a></li>
                        <li><a href="#">Sub Category 6</a></li>
                        <li><a href="#">Sub Category 7</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>

                        <body vlink="#808285 "> </body><a href="#" style="color:#808285">Main Category 4</a>
                    </h4>
                    <ul>
                        <li><a href="#">Sub Category 1</a></li>
                        <li><a href="#">Sub Category 2</a></li>
                        <li><a href="#">Sub Category 3</a></li>
                        <li><a href="#">Sub Category 4</a></li>
                        <li><a href="#">Sub Category 5</a></li>
                        <li><a href="#">Sub Category 6</a></li>
                        <li><a href="#">Sub Category 7</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>

                        <body vlink="#808285 "> </body><a href="#" style="color:#808285">Main Category 5</a>
                    </h4>
                    <ul>
                        <li><a href="#">Sub Category 1</a></li>
                        <li><a href="#">Sub Category 2</a></li>
                        <li><a href="#">Sub Category 3</a></li>
                        <li><a href="#">Sub Category 4</a></li>
                        <li><a href="#">Sub Category 5</a></li>
                        <li><a href="#">Sub Category 6</a></li>
                        <li><a href="#">Sub Category 7</a></li>
                    </ul>
                    <div class="additional-links about-contact">
                        <a href="@Url.Action("AboutUsIndex", "AboutUs")" style="color:#808285">About&nbsp;</a>
                        <a href="@Url.Action("ContactIndex", "Contact")" style="color:#808285">&nbsp;&nbsp;&nbsp;&nbsp;Contact</a>
                    </div>

                    <div class="additional-links faq-help">
                        <a href="#" style="color:#808285">FAQ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
                        <a href="#" style="color:#808285">&nbsp;&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</a>
                    </div>
                </div>

                <div class="followUs">
                    <font color="#828285">
                        <h4>FOLLOW US!</h4>
                        <div class="social-links">
                            <a href="https://youtube.com" target="_blank"><i class="fa-brands fa-youtube" style="line-height: 1.5;"></i></a>
                            <a href="https://facebook.com" target="_blank"><i class="fa-brands fa-facebook" style="line-height: 1.5;"></i></a>
                            <a href="https://instagram.com" target="_blank"><i class="fa-brands fa-instagram" style="line-height: 1.5;"></i></a>
                            <a href="https://linkedin.com" target="_blank"><i class="fa-brands fa-linkedin" style="line-height: 1.5;"></i></a>
                        </div>
                    </font>
                </div>
            </div>
        </div>

        <div class="abovefooter">
            <img src="/Content/WebAssets/IKULogo.svg" />
            <br>

            <img src="/Content/WebAssets/BOOKERRLogo_Gray.svg" />

        </div>


        <div class="footerBottom">
            <p>&copy; Copyright 2023 Istanbul Kultur University Web Programming Group 5 | All rights reserved.
            </p>
            <img class="visa-image" src="/Content//WebAssets/MC_VISA_AE.svg" />

        </div>
    </footer>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

@RenderSection("scripts", required: false)
</body>
</html>