WebProgrammingTerm.MVC/Controllers/AddressController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using SharedLibrary.Mappers;
using WebProgrammingTerm.MVC.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class AddressController : Controller
{
    // GET
    private AddressModel model =new AddressModel();
    public async Task<ActionResult> Addresses()
    {
        var token = Request.Cookies["accessToken"]?.Value;
        if (token is  null)
            return RedirectToAction("SignIn", "Account");
        
        var locationJson = await AddressServices.GetUserLocation(token);
        
        if (!locationJson.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (locationJson["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");
        
        
        var locations = locationJson["data"].ToObject<List<Location>>();
        
        if (TempData.ContainsKey("show") && TempData.TryGetValue("PopUpMessage", out var popMes)  )
        {
            ViewData["show"] = true;
            ViewData["PopUpMessage"] = popMes.ToString();

            TempData.TryGetValue("index", out var index);
            ViewData["index"] = index;
        }

        model.locations = locations;
        return View(model);
    }

    [HttpPost]
    public async Task<ActionResult> AddAddress(AddressModel addressModel)
    {

        var token = Request.Cookies["accessToken"]?.Value;
        if (token is  null)
            return RedirectToAction("SignIn", "Account");

        if (addressModel.clickedIndex >= 0)
        {
            int.TryParse(addressModel.locationUpdateDto.City,out var cityId);
            addressModel.locationUpdateDto.City = addressModel.CityList[cityId-1].Text;
            
            var result = await AddressServices.UpdateUserLocation(addressModel.locationUpdateDto, token);

            if (!result.HasValues)
                return RedirectToAction("Index", "ErrorPage");
            
            if(result["errors"].HasValues)
                return RedirectToAction("Index", "ErrorPage");

            var model = result["data"].ToObject<Location>();
            TempData["PopUpMessage"] = "Address Updated";
            TempData["index"] = addressModel.clickedIndex;

        }
        else
        {
            int.TryParse(addressModel.locationUpdateDto.City,out var cityId);
            addressModel.locationUpdateDto.City = addressModel.CityList[cityId-1].Text;
           
            var result = await AddressServices.AddUserLocation(LocationMapper.ToLocationDto(addressModel.locationUpdateDto),token);
           
           if (!result.HasValues)
               return RedirectToAction("Index", "ErrorPage");
            
           if(result["errors"].HasValues)
               return RedirectToAction("Index", "ErrorPage");
           
           TempData["PopUpMessage"] = "Address created";
        }

        TempData["show"] = true;

        return RedirectToAction("Addresses");
    }


    [HttpPost]
    public async Task<ActionResult> DeleteAddress(string locationIdToDelete)
    {
        var token = Request.Cookies["accessToken"]?.Value;
        if (token is  null)
            return RedirectToAction("SignIn", "Account");
        

        var jObject = await AddressServices.DeleteUserLocation(locationIdToDelete, token);
        if (!jObject.HasValues  )
            return RedirectToAction("Index", "ErrorPage");

        if (jObject["errors"]!.HasValues) 
            return RedirectToAction("Addresses");
        
        TempData["show"] = true;
        TempData["PopUpMessage"] = "Your address successfully deleted";
        

        return RedirectToAction("Addresses");
    }
}

WebProgrammingTerm.MVC/Controllers/CartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using SharedLibrary.DTO;
using SharedLibrary.Models;
using WebProgrammingTerm.MVC.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class CartController : Controller
{
    public CartModel CartModel = new CartModel();
    [HttpPost]
    public async Task<ActionResult> AddToCart(List<string> productIds)
    {
        
        var accessToken = Request.Cookies["accessToken"]?.Value;


        if (accessToken is null)
            return RedirectToAction("SignIn", "Account");

        foreach (var id in productIds)
        {
            var productJsonObject = await ProductServices.GetProduct(id);
            if (!productJsonObject.HasValues)
                return RedirectToAction("Index", "ErrorPage");

            if (productJsonObject["errors"].HasValues)
                return RedirectToAction("Index", "ErrorPage");
            
            CartModel.Products.Add(productJsonObject["data"].ToObject<ProductWCommentDto>());
        }

        var userLocationsObject = await AddressServices.GetUserLocation(accessToken);
        
        if (!userLocationsObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (userLocationsObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");

        var locations = userLocationsObject["data"].ToObject<List<Location>>();
        CartModel.Locations.AddRange(locations);

        TempData["CartContent"] = CartModel;
        return Json(new { success = true,redir=@Url.Action("Index")});
    }
    
    public  ActionResult Index()
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        
        if (accessToken is null)
            return RedirectToAction("SignIn", "Account");
        
        var model = TempData.Peek("CartContent") as CartModel;
        return View("Index", model ?? new CartModel());
    }
    
    [HttpPost]
    public async Task<ActionResult> Index( CartModel cartModel)
    {
        
        var accessToken = Request.Cookies["accessToken"]?.Value;
        
        if (accessToken is null)
            return RedirectToAction("SignIn", "Account");
        
        var model = TempData["CartContent"] as CartModel;

        if (model == null)
            return RedirectToAction("Index", "ErrorPage");
        
        var orderAddDto = new OrderAddDto()
        {
            LocationId = cartModel.ClickedLocation,
            PaymentCard = cartModel.CCNumber,
            ProductIdList = model.Products.Select(p => p.ProductId).ToList(),
            Shipment = "BookerrExpress"
        };

        var result = await CartServices.AddToCart(orderAddDto, accessToken);

        if (!result.HasValues)
            return RedirectToAction("Index", "ErrorPage");
        if (result["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");

        TempData.Clear();
        return RedirectToAction("MyOrders");

    }

    
    [HttpPost]
    public async Task<ActionResult> Remove(string id)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        
        if (accessToken is null)
            return RedirectToAction("SignIn", "Account");
        
        var model = TempData.Peek("CartContent") as CartModel;
        model.Products.Remove(model.Products.FirstOrDefault(p => p.ProductId == id));

        TempData["CartContent"] = model;
        return Json(new { success = true,redir=@Url.Action("Index")});
    }

    [HttpGet]
    public async Task<ActionResult> MyOrders()
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;

        if (accessToken is null)
        {
            return RedirectToAction("SignIn", "Account");
        }
        
        var ordersObject = await CartServices.GetOrders(accessToken);

        if (!ordersObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (ordersObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");


        var orders = ordersObject["data"].ToObject<List<Order>>();

     
        return View(model:orders);
    }



}

WebProgrammingTerm.MVC/Controllers/FavoritesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using SharedLibrary.DTO;
using SharedLibrary.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class FavoritesController : Controller
{
    [HttpPost]
    public async Task<ActionResult> Index(string productId)
    {
        var accessToken = Request.Cookies["accessToken"].Value;

        if (accessToken is null)
            return Json(new { success = true,redir=Url.Action("SignIn","Account")});

        var jsonObject =await FavoritesService.AddToFavorites(productId, accessToken);

        if (!jsonObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (jsonObject["errors"].HasValues)
            return Json(new { success = true,redir=Url.Action("Index","ErrorPage")});

        var data = jsonObject["data"].ToObject<UserFavorites>();
        return Json(new { success = true});
    }
    
    
    
    [HttpGet]
    public async Task<ActionResult> Index()
    {
        var accessToken = Request.Cookies["accessToken"].Value;

        if (accessToken is null)
            return RedirectToAction("SignIn", "Account");

        var userFavoritesObject = await FavoritesService.GetFavorites(accessToken);

        if (!userFavoritesObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (userFavoritesObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");


        var productIds = userFavoritesObject["data"].ToObject<UserFavoritesListDto>();

        var products = new List<Product>();


        foreach (var id in productIds.ProductIds)
        {
             var product = ((await ProductServices.GetProduct(id))["data"].ToObject<Product>());
             product.Id = id;
             products.Add(product);
        }
        return View("MyFavorites" ,model:products);
    }

  
    
}

WebProgrammingTerm.MVC/Controllers/ProfileController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using SharedLibrary.DTO;
using SharedLibrary.Models;
using WebProgrammingTerm.MVC.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class ProfileController : Controller
{
    [HttpGet]
    public async Task<ActionResult> ProfileIndex()
    {
        if (TempData["ModelState"] is ModelStateDictionary modelState)
            ModelState.Merge(modelState);

        if (TempData.ContainsKey("PasswordChanged"))
        
            ViewData["PasswordChanged"] = true;

        var token = Request.Cookies["accessToken"]?.Value;
        
        if (token is null) 
            return RedirectToAction("SignIn", "Account");
        
        var userJson = await UserServices.GetUserProfileInfo(token);
        
        if (!userJson.HasValues)
        {
            Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1);

            return RedirectToAction("Index", "ErrorPage");
        }
        
        var userData = userJson["data"];
        var user = userData.ToObject<User>();
        
        
        return View(new UserModels()
        {
            User = user
        });
    }
    
    
    [HttpPost]
    public async Task<ActionResult> SaveProfile(AppUserUpdateDto appUserUpdateDto,string birthdate)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        var refreshToken = Request.Cookies["refreshToken"]?.Value;
        
        if (string.IsNullOrEmpty(accessToken) || string.IsNullOrEmpty(refreshToken))
            return RedirectToAction("SignIn", "Account");

        
        var userJson = await UserServices.UpdateUserProfile(appUserUpdateDto,accessToken);

        if (!userJson.HasValues)
            return RedirectToAction("Index", "ErrorPage");
        
        var userRefreshTokenJson =await UserServices.CreateTokenByRefreshToken(refreshToken);
        
        Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
        Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1);
        
        if (!userRefreshTokenJson.HasValues)
            return RedirectToAction("Index", "ErrorPage");
        

        var cookies = UserServices.AddCookies(userRefreshTokenJson);
        foreach (var cookie in cookies)
        {
            Response.Cookies.Add(cookie);
        }
        appUserUpdateDto.BirthDate = birthdate;
        
        return RedirectToAction("ProfileIndex");

    }

    [HttpPost]
    public async Task<ActionResult> UpdatePassword(UserUpdatePasswordDto userUpdatePasswordDto)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        var refreshToken = Request.Cookies["refreshToken"]?.Value;
        TempData["PasswordChanged"] = false;

        if (string.IsNullOrEmpty(accessToken) || string.IsNullOrEmpty(refreshToken))
            return RedirectToAction("SignIn", "Account");

        if (string.CompareOrdinal(userUpdatePasswordDto.NewPassword, userUpdatePasswordDto.NewPasswordConfirm) != 0)
        {
            ModelState.AddModelError("Password","Password and Confirm password does not match");
            return RedirectToAction("ProfileIndex");
        }

        var jsonObject = await UserServices.UpdateUserPassword(userUpdatePasswordDto, accessToken);
        if (!jsonObject.HasValues)
        {
            Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1);
            RedirectToAction("Index", "ErrorPage");
        }
        if (!jsonObject["errors"]!.HasValues)
        {
            Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1); 
            
            var cookies =UserServices.AddCookies(jsonObject);
            
            foreach (var cookie in cookies)
            {
                Response.Cookies.Add(cookie);
            }
            TempData["PasswordChanged"] = true;

        }
        else
        {
            foreach (var error in jsonObject["errors"])
            {
                if (error.ToString().Contains("ssword")  )
                    ModelState.AddModelError("Password",$"{error}");
            }
            TempData["ModelState"] = ModelState;

        }
        return RedirectToAction("ProfileIndex");
    }
    

}

WebProgrammingTerm.MVC/Views/Address/Addresses.cshtml
@model WebProgrammingTerm.MVC.Models.AddressModel

<head>
    <title>My Addresses</title>

    <link rel="stylesheet" type="text/css" href="../../Content/BookerrCSS/profile.css?v27">
    <link rel="stylesheet" type="text/css" href="../../Content/BookerrCSS/address.css?v39">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <script src="~/Scripts/BookerrScripts/AddressCarosel.js?v7" defer></script>
    <script src="~/Scripts/BookerrScripts/AddressPage.js?v11"></script>


</head>

<body>

    @if (ViewData["show"] is bool show && show)
    {
        <div class="popup-container" id="popup" >
            <div class="popup-content">
                <div class="checkmark">✔</div>
                <p>@ViewData["PopUpMessage"]</p>
                <button class="close-btn" onclick="closePopup()">Close</button>
            </div>
        </div>
        
        <script>
        showPopup()
        </script>
        
    }

<div class="mainContent">
    <div class="profileContent"style="height: 100%">
        <div class="profile_section">
            <div class="link_holder">
                <div class="profile_sections">
                    <a href="@Url.Action("ProfileIndex", "Profile")"><button type="button">Profile Details</button></a>
                    <a href="@Url.Action("Addresses", "Address")"><button type="button" style="color: white; background-color: #808285">My Addresses</button></a>
                    <a href="@Url.Action("Index","Favorites")"><button type="button">My Favorites</button></a>
                    <a href="@Url.Action("MyOrders","Cart")"><button type="button">My Orders</button></a>
                    <a href="@Url.Action("SignOut","Account")"><button type="button" style="padding-bottom: 1%">Sign Out</button></a>
                </div>
            </div>
        </div>
        <div class="address">
            <div class="my_address">

                @foreach (var location in Model.locations)
                {
                    <div class="addressInfo" id = "@location.Id">

                        <h3 style=" font-size: 16px; font-weight: 700">@location.Title</h3>
                        <content>
                            @{
                                var fullAddress = location.Address + location.City + location.ZipCode;
                                var truncatedName = fullAddress.Length > 60
                                    ? fullAddress.Substring(0, 57) + "..."
                                    : fullAddress;
                                
                            }
                            <p style=" font-size: 14px; font-weight: 500;">
                                @truncatedName
                            </p>
                            <a class="pen"><i class="fa-solid fa-pen" onclick='SetClickedIndex(@Model.locations.IndexOf(location)) ;ShowAddressInfo(@Model.locations.IndexOf(location), "@location.Id", "@location.Title", "@location.Address", "@location.City", "@location.ZipCode")'></i></a>

                            <form action="@Url.Action("DeleteAddress")" method="POST" id="deleteForm">
                                @Html.Hidden("locationIdToDelete", "")

                                    <a class="tbag" onclick="confirmDelete(@Model.locations.IndexOf(location),'@location.Id');">
                                        <button type="button" class="save-button" style="border: none; background: none; padding: 0;">
                                            <i class="fas fa-trash-can" style="color: inherit;"></i>
                                        </button>
                                    </a>
                            </form>


                            <div class="popup-container" id="confirmationPopup" style="display: none;">
                                <div class="popup-content">
                                    <div class="warning-sign">⚠️</div>
                                    <p>Are you sure you want to delete @location.Title </p>
                                    <button class="close-btn" onclick="confirmAndSubmit()">Yes</button>
                                    <button class="close-btn" style="background-color: red" onclick="closeConfirmationPopup()">No</button>
                                </div>
                            </div>

                        </content>
                        
                    </div>
                }

                <div class="addition" onclick="ResetAddress()">
                    <a href="#" class="addition-link">+</a>
                </div>
            </div>
                <div class="add-address" style="display: @(@ViewData["show"] is bool ? "block" : "none");">
                <form action="@Url.Action("AddAddress", "Address")" method="POST">

                    <h2>Add Addresses</h2>
                    @Html.HiddenFor(m => m.clickedIndex)
                    @Html.HiddenFor(m => m.locationUpdateDto.Id, new { id = "locationUpdateDto_Id" })

                    @Html.TextBoxFor(m => m.locationUpdateDto.Title, new { @class = "title-input", id = "title-input", style = "margin-bottom: 1%;", placeholder = "Address Title", required = "required" })
                    @Html.TextBoxFor(m => m.locationUpdateDto.Address, new { @class = "address-input", id = "address-input", style = "height: 40%; border-radius: 15px;margin-bottom: 2%", placeholder = "Address", required = "required" })

                    <div class="address-bars" style="margin-bottom: 2%">
                        <div class="city-bar">
                            @Html.DropDownListFor(m => m.locationUpdateDto.City, new SelectList(Model.CityList, "Value", "Text"), new { @class = "city", id = "city", required = "required" })

                        </div>
                        <div class="zipcode-bar">
                            @Html.TextBoxFor(m => m.locationUpdateDto.ZipCode, new { @class = "zipcode", id = "zipcode", placeholder = "Zip Code", required = "required" })
                        </div>
                    </div>
                    <button type="submit" class="save-button">Save</button>

                </form>
            </div>
            @{
                if (ViewData["show"] is bool show_ && show_ && ViewData["PopUpMessage"].ToString() != "Address created" && ViewData["PopUpMessage"].ToString() !="Your address successfully deleted")
                {
                    int.TryParse( ViewData["index"].ToString(),out var index);
                    var loc = Model.locations[index];
                    <script>
                    ShowAddressInfo(@index, "@loc.Id", "@loc.Title", "@loc.Address", "@loc.City", "@loc.ZipCode")
                    </script>
                }
            }
        </div>

    </div>
</div>
<script>

</script>
</body> 