WebProgrammingTerm.MVC/Controllers/AddressController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using SharedLibrary.Mappers;
using WebProgrammingTerm.MVC.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class AddressController : Controller
{
    // GET
    private AddressModel model =new AddressModel();
    public async Task<ActionResult> Addresses()
    {
        var token = Request.Cookies["accessToken"]?.Value;
        if (token is  null)
            return RedirectToAction("SignIn", "Account");
        
        var locationJson = await AddressServices.GetUserLocation(token);
        
        if (!locationJson.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (locationJson["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");
        
        
        var locations = locationJson["data"].ToObject<List<Location>>();
        
        if (TempData.ContainsKey("show") && TempData.TryGetValue("PopUpMessage", out var popMes)  )
        {
            ViewData["show"] = true;
            ViewData["PopUpMessage"] = popMes.ToString();

            TempData.TryGetValue("index", out var index);
            ViewData["index"] = index;
        }

        model.locations = locations;
        return View(model);
    }

    [HttpPost]
    public async Task<ActionResult> AddAddress(AddressModel addressModel)
    {

        var token = Request.Cookies["accessToken"]?.Value;
        if (token is  null)
            return RedirectToAction("SignIn", "Account");

        if (addressModel.clickedIndex >= 0)
        {
            int.TryParse(addressModel.locationUpdateDto.City,out var cityId);
            addressModel.locationUpdateDto.City = addressModel.CityList[cityId-1].Text;
            
            var result = await AddressServices.UpdateUserLocation(addressModel.locationUpdateDto, token);

            if (!result.HasValues)
                return RedirectToAction("Index", "ErrorPage");
            
            if(result["errors"].HasValues)
                return RedirectToAction("Index", "ErrorPage");

            var model = result["data"].ToObject<Location>();
            TempData["PopUpMessage"] = "Address Updated";
            TempData["index"] = addressModel.clickedIndex;

        }
        else
        {
            int.TryParse(addressModel.locationUpdateDto.City,out var cityId);
            addressModel.locationUpdateDto.City = addressModel.CityList[cityId-1].Text;
           
            var result = await AddressServices.AddUserLocation(LocationMapper.ToLocationDto(addressModel.locationUpdateDto),token);
           
           if (!result.HasValues)
               return RedirectToAction("Index", "ErrorPage");
            
           if(result["errors"].HasValues)
               return RedirectToAction("Index", "ErrorPage");
           
           TempData["PopUpMessage"] = "Address created";
        }

        TempData["show"] = true;

        return RedirectToAction("Addresses");
    }


    [HttpPost]
    public async Task<ActionResult> DeleteAddress(string locationIdToDelete)
    {
        var token = Request.Cookies["accessToken"]?.Value;
        if (token is  null)
            return RedirectToAction("SignIn", "Account");
        

        var jObject = await AddressServices.DeleteUserLocation(locationIdToDelete, token);
        if (!jObject.HasValues  )
            return RedirectToAction("Index", "ErrorPage");

        if (jObject["errors"]!.HasValues) 
            return RedirectToAction("Addresses");
        
        TempData["show"] = true;
        TempData["PopUpMessage"] = "Your address successfully deleted";
        

        return RedirectToAction("Addresses");
    }
}

WebProgrammingTerm.MVC/Controllers/CartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using SharedLibrary.DTO;
using SharedLibrary.Models;
using WebProgrammingTerm.MVC.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class CartController : Controller
{
    public CartModel CartModel = new CartModel();
    [HttpPost]
    public async Task<ActionResult> AddToCart(List<string> productIds)
    {
        
        var accessToken = Request.Cookies["accessToken"]?.Value;


        if (accessToken is null)
            return RedirectToAction("SignIn", "Account");

        foreach (var id in productIds)
        {
            var productJsonObject = await ProductServices.GetProduct(id);
            if (!productJsonObject.HasValues)
                return RedirectToAction("Index", "ErrorPage");

            if (productJsonObject["errors"].HasValues)
                return RedirectToAction("Index", "ErrorPage");
            
            CartModel.Products.Add(productJsonObject["data"].ToObject<ProductWCommentDto>());
        }

        var userLocationsObject = await AddressServices.GetUserLocation(accessToken);
        
        if (!userLocationsObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (userLocationsObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");

        var locations = userLocationsObject["data"].ToObject<List<Location>>();
        CartModel.Locations.AddRange(locations);

        TempData["CartContent"] = CartModel;
        return Json(new { success = true,redir=@Url.Action("Index")});
    }
    
    public  ActionResult Index()
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        
        if (accessToken is null)
            return RedirectToAction("SignIn", "Account");
        
        var model = TempData.Peek("CartContent") as CartModel;
        return View("Index", model ?? new CartModel());
    }
    
    [HttpPost]
    public async Task<ActionResult> Index( CartModel cartModel)
    {
        
        var accessToken = Request.Cookies["accessToken"]?.Value;
        
        if (accessToken is null)
            return RedirectToAction("SignIn", "Account");
        
        var model = TempData["CartContent"] as CartModel;

        if (model == null)
            return RedirectToAction("Index", "ErrorPage");
        
        var orderAddDto = new OrderAddDto()
        {
            LocationId = cartModel.ClickedLocation,
            PaymentCard = cartModel.CCNumber,
            ProductIdList = model.Products.Select(p => p.ProductId).ToList(),
            Shipment = "BookerrExpress"
        };

        var result = await CartServices.AddToCart(orderAddDto, accessToken);

        if (!result.HasValues)
            return RedirectToAction("Index", "ErrorPage");
        if (result["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");

        TempData.Clear();
        return RedirectToAction("MyOrders");

    }

    
    [HttpPost]
    public async Task<ActionResult> Remove(string id)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        
        if (accessToken is null)
            return RedirectToAction("SignIn", "Account");
        
        var model = TempData.Peek("CartContent") as CartModel;
        model.Products.Remove(model.Products.FirstOrDefault(p => p.ProductId == id));

        TempData["CartContent"] = model;
        return Json(new { success = true,redir=@Url.Action("Index")});
    }

    [HttpGet]
    public async Task<ActionResult> MyOrders()
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;

        if (accessToken is null)
        {
            return RedirectToAction("SignIn", "Account");
        }
        
        var ordersObject = await CartServices.GetOrders(accessToken);

        if (!ordersObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (ordersObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");


        var orders = ordersObject["data"].ToObject<List<Order>>();

     
        return View(model:orders);
    }



}

WebProgrammingTerm.MVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using SharedLibrary.DTO;
using WebProgrammingTerm.MVC.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class ProductController : Controller
{
    public async Task<ActionResult> Index(string id)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        var productJsonObject = await ProductServices.GetProduct(id);

        if (!productJsonObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (productJsonObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");


        if (accessToken is not null)
        {
            var userJsonObject = await FavoritesService.GetFavorites(accessToken);
        
            if (!userJsonObject.HasValues)
                return RedirectToAction("Index", "ErrorPage");

            if (userJsonObject["errors"].HasValues)
                return RedirectToAction("Index", "ErrorPage");
            var model = new ProductModel()
            {
                ProductWGetDto = productJsonObject["data"].ToObject<ProductWCommentDto>(),
                UserFavoritesDto = userJsonObject["data"].ToObject<UserFavoritesListDto>()
            };
            model.ProductWGetDto.Size = productJsonObject["data"]["productDetail"]["size"].ToString();

            return View(model);

        }
        else
        {
            var model = new ProductModel()
            {
                ProductWGetDto = productJsonObject["data"].ToObject<ProductWCommentDto>(),
                UserFavoritesDto = new UserFavoritesListDto()
            };
            return View(model);
        }
        
    }
    public async Task<ActionResult> Search(string searchTerm = "",int page = 1)
    {

        if (page < 1)
        {
            page = 1;
        }
        var productObject = await ProductServices.GetProductFromName(searchTerm, page);

        if (!productObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (productObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");


        ViewData["searchterm"] = searchTerm;
        ViewData["page"] = page;
        var products = productObject["data"].ToObject<List<ProductGetDto>>() ?? new List<ProductGetDto>();



        return View(products);
    }

    public async Task<ActionResult> SearchByCategory(string searchTerm = "",int page = 1)
    {

        if (page < 1)
        {
            page = 1;
        }
        var productObject = await ProductServices.GetProductFromCategory(searchTerm, page);

        if (!productObject.HasValues)
            return RedirectToAction("Index", "ErrorPage");

        if (productObject["errors"].HasValues)
            return RedirectToAction("Index", "ErrorPage");


        ViewData["searchterm"] = searchTerm;
        ViewData["page"] = page;

        var products = productObject["data"].ToObject<List<ProductGetDto>>();

        if (products is null)
        {
            products = new List<ProductGetDto>();
        }
        
        if (products.Count ==0 && page >2)
        {
            ViewData["NXT"] = false;

            return RedirectToAction("SearchByCategory", new { searchTerm = searchTerm, page = page-1 });
            
        }
        ViewData["NXT"] = true;

        return View("Search",products);
    }

 
}

WebProgrammingTerm.MVC/Controllers/ProfileController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using SharedLibrary.DTO;
using SharedLibrary.Models;
using WebProgrammingTerm.MVC.Models;
using WebProgrammingTerm.MVC.Services;

namespace WebProgrammingTerm.MVC.Controllers;

public class ProfileController : Controller
{
    [HttpGet]
    public async Task<ActionResult> ProfileIndex()
    {
        if (TempData["ModelState"] is ModelStateDictionary modelState)
            ModelState.Merge(modelState);

        if (TempData.ContainsKey("PasswordChanged"))
        
            ViewData["PasswordChanged"] = true;

        var token = Request.Cookies["accessToken"]?.Value;
        
        if (token is null) 
            return RedirectToAction("SignIn", "Account");
        
        var userJson = await UserServices.GetUserProfileInfo(token);
        
        if (!userJson.HasValues)
        {
            Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1);

            return RedirectToAction("Index", "ErrorPage");
        }
        
        var userData = userJson["data"];
        var user = userData.ToObject<User>();
        
        
        return View(new UserModels()
        {
            User = user
        });
    }
    
    
    [HttpPost]
    public async Task<ActionResult> SaveProfile(AppUserUpdateDto appUserUpdateDto,string birthdate)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        var refreshToken = Request.Cookies["refreshToken"]?.Value;
        
        if (string.IsNullOrEmpty(accessToken) || string.IsNullOrEmpty(refreshToken))
            return RedirectToAction("SignIn", "Account");

        
        var userJson = await UserServices.UpdateUserProfile(appUserUpdateDto,accessToken);

        if (!userJson.HasValues)
            return RedirectToAction("Index", "ErrorPage");
        
        var userRefreshTokenJson =await UserServices.CreateTokenByRefreshToken(refreshToken);
        
        Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
        Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1);
        
        if (!userRefreshTokenJson.HasValues)
            return RedirectToAction("Index", "ErrorPage");
        

        var cookies = UserServices.AddCookies(userRefreshTokenJson);
        foreach (var cookie in cookies)
        {
            Response.Cookies.Add(cookie);
        }
        appUserUpdateDto.BirthDate = birthdate;
        
        return RedirectToAction("ProfileIndex");

    }

    [HttpPost]
    public async Task<ActionResult> UpdatePassword(UserUpdatePasswordDto userUpdatePasswordDto)
    {
        var accessToken = Request.Cookies["accessToken"]?.Value;
        var refreshToken = Request.Cookies["refreshToken"]?.Value;
        TempData["PasswordChanged"] = false;

        if (string.IsNullOrEmpty(accessToken) || string.IsNullOrEmpty(refreshToken))
            return RedirectToAction("SignIn", "Account");

        if (string.CompareOrdinal(userUpdatePasswordDto.NewPassword, userUpdatePasswordDto.NewPasswordConfirm) != 0)
        {
            ModelState.AddModelError("Password","Password and Confirm password does not match");
            return RedirectToAction("ProfileIndex");
        }

        var jsonObject = await UserServices.UpdateUserPassword(userUpdatePasswordDto, accessToken);
        if (!jsonObject.HasValues)
        {
            Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1);
            RedirectToAction("Index", "ErrorPage");
        }
        if (!jsonObject["errors"]!.HasValues)
        {
            Response.Cookies["accessToken"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["refreshToken"].Expires = DateTime.Now.AddDays(-1); 
            
            var cookies =UserServices.AddCookies(jsonObject);
            
            foreach (var cookie in cookies)
            {
                Response.Cookies.Add(cookie);
            }
            TempData["PasswordChanged"] = true;

        }
        else
        {
            foreach (var error in jsonObject["errors"])
            {
                if (error.ToString().Contains("ssword")  )
                    ModelState.AddModelError("Password",$"{error}");
            }
            TempData["ModelState"] = ModelState;

        }
        return RedirectToAction("ProfileIndex");
    }
    

}

WebProgrammingTerm.MVC/Views/Cart/Index.cshtml
@using System.Globalization
@model WebProgrammingTerm.MVC.Models.CartModel

<head>
    <link rel="stylesheet" type="text/css" href="../../Content/BookerrCSS/profile.css">
    <link rel="stylesheet" type="text/css" href="../../Content/BookerrCSS/address.css?v39">
    <link rel="stylesheet" type="text/css" href="../../Content/BookerrCSS/order.css?v3">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="../../Scripts/BookerrScripts/CartPage.js" ></script>
    <script src="../../Scripts/BookerrScripts/AddressCarosel.js?v7"></script>
    <title>Cart</title>

    <style>
        
         .carousel-next-btn {
             position: absolute;
             margin-top: 7%;
             left: 85%;
        
         }
        
         .carousel-prev-btn {
             position: absolute;
             margin-top: 7%;
         }
    </style>
</head>

<body>
    
<div class="mainContent" style="height: fit-content">
    
    @if (Model.Products.Count > 0)
    {
        
        <div class="profile_section" style="height: 100%">
    
        <div class="link_holder" style="height: auto;">
            <h2 id="profile_header" style="margin-top: -195%; margin-left:-135%;  width: auto;">Order</h2>

        </div>

        <div class="productcontainer">
            @{
                var totalPrice = 0f;
                foreach (var product in Model.Products)
                {
                    var name = product.Publisher.Replace("-", " ");
                    var titleCaseName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(name);
                    <div id="product-@product.ProductId" style="height: fit-content">
                        <div id="productContent">
                            <div class="tcan">
                                <a href="#" onclick="removeProduct('@product.ProductId')"><i id="trash-can-@product.ProductId" class="fa-regular fa-trash-can"
                                                                                             style="color:#F47878"></i>
                                </a>
                            </div>
                            <p id ="priceText">@product.Price₺</p>

                            <div id="productImage">
                                <a href="@Url.Action("Index", "Product", new { id = @product.ProductId })">
                                    <img src="@product.ImagePath"/>

                                </a>
                            </div>

                            <div id="productInfo">
                                <p style="font-weight: 700">@titleCaseName</p>
                                <p>@product.Name</p>
                                <p>@product.Author</p>
                            </div>

                        </div>

                    </div>
                    totalPrice += product.Price;
                }
            }
        </div>
        <hr style=" border-color: black; margin-top: 1.5%; border-width: 1px; ">

            <p style="margin-top:1%; margin-left: 65%;">Product Total &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                &nbsp;@totalPrice₺</p>


            <hr style=" border-color: black; margin-top: 1.5%; border-width: 1px; width: 40%; margin-left: 60%; ">

            <p style=" margin-left: 57%; font-size:20px; font-weight:700;">&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;Total
                Price: &nbsp; &nbsp; &nbsp; &nbsp;@totalPrice₺</p>
        

            <div class="address">
                <div class="my_address">

                    @foreach (var location in Model.Locations)
                    {
                        <div class="addressInfo" id="@location.Id" >
                            <a style="text-decoration: none; color: black; cursor:pointer;" onclick="highLightAddress('@location.Id');SetClickedLocation('@location.Id')">
                                <h3 style=" font-size: 16px; font-weight: 700">@location.Title</h3>
                                <content>
                                    <p style=" font-size: 14px; font-weight: 500;">@location.Address @location.City
                                        @location.ZipCode
                                    </p>
                                </content>
                            </a>
                        </div>
                    }
                    <div class="addition" >
                        <a href="@Url.Action("Addresses","Address")" target = "_blank"class="addition-link">+</a>
                    </div>
                </div>

            </div>

        @if (Model.Products.Count > 0)
        {
                
            <div class="payment-section">
            <h2 style="font-size: 32px; margin-top: 3%;">Payment</h2>
            <form action="@Url.Action("Index", "Cart")" method="POST" onsubmit="return validateForm()">
                
                <div class="payment-fields">
                    <div class="cardinfo">
                        @Html.HiddenFor(m => m.ClickedLocation, new { @required = "required" })

                        @Html.TextBoxFor(m=>m.FirstNameCC,new {type="text", id="name" ,placeholder="First Name" ,name="name", required="required",
                            style="width: 48%; padding: 13px; margin-bottom: 1.5%;"})
                        
                         @Html.TextBoxFor(m=>m.LastNameCC,new {type="text", id="surname", placeholder="Last Name", name="surname", required="required",
                             style="width: 48%;  margin-top: -7.5%; padding: 13px;"})
                        
                        
                        @Html.TextBoxFor(m=>m.CCNumber, new {type="number", id="cardNumber", placeholder="Credit Card Number", name="required",
                            required="reqiured", style="width: 48%; padding: 13px;"})
                        
                        
                        @Html.TextBoxFor(m=>m.CVC, new {type="number", id="cvv", placeholder="CVC", name="cvv", required = "required",
                            style="width: 48%;  margin-top: -6%; padding: 13px;"})
           
                    </div>
                </div>
                
                <div class="card_date">
                    <p style="color:#808285; width:24%; font-weight:700; font-size:20px; margin-top:3%;">Card Expiration:
                    </p>
                    <div style=" margin-top: -5%;">
                        <select id="cardMonth" name="cardMonth" style="width: 8%; margin-left: 27%;">
                            @for (var i = 1; i <= 12; i++)
                            {
                                <option >@i</option>
                            }
                        </select>
                        <select id="cardYear" name="cardYear" style="width: 10%; margin-left: 0.5%;">
                            @for (var i = 2045; i >= DateTime.Now.Year; i--)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                    </div>
                </div>
                <input type="radio" id="agreement" name="agreement" required="required"
                    style="width: 7%; height: 7%; margin-top: 5%; margin-left: -1%; accent-color: grey;">
                <p style="margin-top: -2.5%; margin-left: 6%;">
                    I have read and approve the <a href="#" style="color: blue;">Distance Sales Agreement.</a>
                </p>
                <button type="submit" class="save-button">Confirm Order</button>

            </form>

        </div>
    
        }

        </div>

        
    }



    </div>
<script>
    function removeProduct(productId) {
        $.ajax({
            url: '@Url.Action("Remove", "Cart")',
            type: 'POST',
            data: { id: productId },
            success: function (data) {
                $('#product-' + productId).remove();
            
                var cartItems = JSON.parse(localStorage.getItem('cart')) || [];
            
                var index = cartItems.indexOf(productId);
            
                if (index !== -1) {
                    cartItems.splice(index, 1);
                }
            
                localStorage.setItem('cart', JSON.stringify(cartItems));
                
                if (data.redir)
                    window.location.href = data.redir
            },
            error: function () {
                alert('Error removing product.');
            }
        });
    }
    
    function highLightAddress(id)
    {
        
        var allElements = document.getElementsByClassName("addressInfo");
        for (var i = 0; i < allElements.length; i++) {
            if (allElements[i].id === id)
            {
                allElements[i].style.borderColor = "#4cae4c";
            }else
            {                    
                allElements[i].style.borderColor = "#E6E7E8";
            }
        }
    }
    function  SetClickedLocation(value)
    {
        document.getElementById("ClickedLocation").value = value;
    
    }
    
    function validateForm() {
        var form = document.querySelector('form');
            var clickedLocation = document.getElementById("ClickedLocation").value;

        if (clickedLocation === "") {
            alert("Please select a home address before submitting the form.");
            return false; 

        }
        
        if (form.checkValidity())
        {
            localStorage.removeItem('cart')
            return true; 
        } else 
        {
            return false; 
        }
    }
</script>
</body>

WebProgrammingTerm.MVC/Views/Cart/MyOrders.cshtml
@using System.Globalization
@model List<SharedLibrary.Models.Order>

<head>
    
    <link rel="stylesheet" type="text/css" href="/Content/BookerrCSS/profile.css?v26">
    <link rel="stylesheet" type="text/css" href="/Content/BookerrCSS/MyOrders.css?v1">
    <link rel="stylesheet" type="text/css" href="/Content/BookerrCSS/ProductCard.css">
    <link rel="stylesheet" type="text/css" href="/Content/BookerrCSS/ProductCardCarosel.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <title>My Orders</title>

        
</head>

<body>
<div class="mainContent">
    <div class="popup-container" id="popup" style="display: none">
        <div class="popup-content">
            <div class="checkmark">✔</div>
            <p>Product added to cart</p>
            <button class="close-btn" onclick="closePopup()">Close</button>
        </div>
    </div>
    <div class="profileContent">
        <div class="profile_section">
            <div class="link_holder">
                <div class="profile_sections">
                    <a href="@Url.Action("ProfileIndex", "Profile")"><button type="button" >Profile Details</button></a>
                    <a href="@Url.Action("Addresses", "Address")"><button type="button">My Addresses</button></a>
                    <a href="@Url.Action("Index", "Favorites")"><button type="button" >My Favorites</button></a>
                    <a href="@Url.Action("MyOrders","Cart")"><button type="button" style="color: white; background-color: #808285">My Orders</button></a>
                    <a href="@Url.Action("SignOut","Account")"><button type="button">Sign Out</button></a>
                </div>
            </div>
        </div>
    </div>
    
    <div class="ordersContainer">
        @foreach (var order in Model)
        {
            var total = 0f;
            <div class="orderText">
                <p>Shipped To Address @order.Location.Title, Zip Code @order.Location.ZipCode</p>
                <p>Paid With @order.OrderDetail.PaymentMethod</p>
            </div>
            <div class="orderContainer">
                
                @foreach (var product in order.Products)
                {
                    <a src="#" href="@Url.Action("Index", "Product", new { id = product.Id })">

                        <div class="product-carousel-item" style="margin-bottom: 5%">
                            <div class="card" style="width: 18rem;">
                                <img src="@product.ImagePath" class="card-img-top" alt="productImage">
                                <div class="card-body">
                                    <p class="card-text">
                                        <strong class="card-title">
                                            <a style="color:inherit">
                                                @{
                                                    var name = product.ProductDetail.Publisher.Replace("-", " ");
                                                    var titleCaseName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(name);

                                                }
                                                @titleCaseName
                                            </a><br/>
                                        </strong>
                                        @{
                                            var truncatedName = product.Name.Length > 60
                                                ? product.Name.Substring(0, 57) + "..."
                                                : product.Name;
                                        }
                                        @truncatedName
                                        <div class="carosel-product-info">

                                            <p class="carosel-product-info-text" style="margin-top: 15px">@product.Price₺</p>
                                        </div>
                                    </p>
                                </div>
                            </div>
                        </div>

                    </a>
                    total += product.Price;

                }
            </div>

        }
        
    </div>
</div>

<script>

    function showPopup() {
        document.getElementById('popup').style.display = 'block';
    }
    
    function closePopup() {
        document.getElementById('popup').style.display = 'none';
    }

</script>

</body>